from io import BytesIO
from datetime import datetime


def generate_photocopy_pdf(submission, exam):
    from reportlab.lib.pagesizes import A4
    from reportlab.pdfgen import canvas

    buffer = BytesIO()
    c      = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    def draw_watermark():
        c.saveState()
        c.setFont("Helvetica-Bold", 60)
        c.setFillColorRGB(0.85, 0.85, 0.85)
        c.setFillAlpha(0.3)
        c.translate(width / 2, height / 2)
        c.rotate(45)
        c.drawCentredString(0, 0, "PHOTOCOPY")
        c.restoreState()

    def draw_header():
        c.setFont("Helvetica-Bold", 16)
        c.setFillColorRGB(0.35, 0.24, 0.21)
        c.drawString(60, height - 60, "GRADY — AI Examiner")
        c.setFont("Helvetica", 11)
        c.setFillColorRGB(0, 0, 0)
        c.drawString(60, height - 82,  f"Exam: {exam.title}  |  Subject: {exam.subject}")
        c.drawString(60, height - 100, f"Roll No: {submission.roll_number}  |  Division: {exam.division}  |  Class: {exam.class_name}")
        c.drawString(60, height - 118, f"Total Marks: {submission.total_marks} / {submission.max_marks}  |  Grade: {submission.grade}")
        c.line(60, height - 130, width - 60, height - 130)

    draw_watermark()
    draw_header()

    y         = height - 155
    eval_data = submission.evaluation_json or {}

    c.setFont("Helvetica-Bold", 13)
    c.setFillColorRGB(0.35, 0.24, 0.21)
    c.drawString(60, y, "Answer Sheet — Question Wise Breakdown")
    y -= 25

    for qid, data in eval_data.items():
        if data.get("ignored_due_to_best_of"):
            continue

        if y < 120:
            c.showPage()
            draw_watermark()
            y = height - 60

        c.setFont("Helvetica-Bold", 11)
        c.setFillColorRGB(0.35, 0.24, 0.21)
        c.drawString(60, y, f"{qid}  —  Marks Awarded: {data.get('final_marks', 0)} / {data.get('max_marks', 0)}")
        y -= 18

        reasoning  = data.get("reasoning", {})
        components = reasoning.get("components", [])

        for comp in components:
            if y < 80:
                c.showPage()
                draw_watermark()
                y = height - 60

            status = comp.get("status", "")
            name   = comp.get("component", "")
            reason = comp.get("reasoning", "")
            line   = f"  {status}  {name} — {reason}"

            c.setFont("Helvetica", 9)
            c.setFillColorRGB(0, 0, 0)

            if len(line) > 100:
                c.drawString(65, y, line[:100])
                y -= 13
                if y < 80:
                    c.showPage()
                    draw_watermark()
                    y = height - 60
                c.drawString(75, y, line[100:200])
            else:
                c.drawString(65, y, line)
            y -= 13

        feedback = reasoning.get("overall_feedback", "")
        if feedback:
            if y < 80:
                c.showPage()
                draw_watermark()
                y = height - 60
            c.setFont("Helvetica-Oblique", 9)
            c.setFillColorRGB(0.4, 0.4, 0.4)
            short = feedback[:120] + "..." if len(feedback) > 120 else feedback
            c.drawString(65, y, f"Feedback: {short}")
            y -= 13

        y -= 10

    c.setFont("Helvetica", 9)
    c.setFillColorRGB(0.5, 0.5, 0.5)
    c.drawCentredString(
        width / 2, 35,
        f"Generated by GRADY AI Examiner  |  {datetime.utcnow().strftime('%d %b %Y %H:%M')}  |  OFFICIAL PHOTOCOPY"
    )

    c.save()
    buffer.seek(0)
    return buffer